### ISSUE TITLE
logging module not compatible with Python 3?

### ISSUE THREAD

**Issue by jbeale1** [ssesselmann/impulse#24]
attempting to install the prerequisites on Windows 10, I encountered this problem while installing "logging" :
```
>pip install -r requirements_pc.txt
...
Collecting logging
  Downloading logging-0.4.9.6.tar.gz (96 kB)
     ---------------------------------------- 96.0/96.0 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error        File "C:\Users\beale\AppData\Local\Temp\pip-install-3v5363by\logging_8749368d85734bec91088b5e85bed926\logging\__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]

  × python setup.py egg_info did not run successfully.
```
It is apparently this error: https://stackoverflow.com/questions/32386469/logging-module-not-working-with-python3

**Comment by jbeale1** [comment]
My Python installation is likely messed up in some nonstandard way. I eventually got Impulse to run, without installing "logging" but using pip to 
separately and manually install many of the packages that the requirements_pc.txt file already seems to include.

**Comment by ssesselmann** [comment]
Thanks for reporting, my mistake for attempting to install logging, apparently logging is already built in to python3, so it does not require installing. This morning I also tidied yup the logging on all the pages, so good idea to get the latest version.

Steven

**Comment by ssesselmann** [comment]
This issue is closed
